PRODUCTS = [
    {
        "name": "Airpods Wireless Bluetooth Headphones",
        "brand": "Apple",
        "category": "Electronics",
        "description": "Bluetooth technology lets you connect with compatible devices wirelessly. High-quality AAC audio offers an immersive listening experience and the built-in microphone makes calls easy.",
        "price": "25000.00",
        "rating": "4.50",
        "review_count": 125,
        "count_in_stock": 7,
        "image": "/assets/airpods.svg",
    },
    {
        "name": "iPhone 15 Pro Max 256GB",
        "brand": "Apple",
        "category": "Mobiles",
        "description": "Titanium design, powerful A17 Pro performance, crisp Super Retina display, and a pro camera system for everyday photos and video.",
        "price": "99999.00",
        "rating": "4.50",
        "review_count": 1000,
        "count_in_stock": 4,
        "image": "/assets/iphone.svg",
    },
    {
        "name": "Cannon EOS 80D DSLR Camera",
        "brand": "Cannon",
        "category": "Cameras",
        "description": "A versatile DSLR camera for crisp photography, full HD video, fast autofocus, and dependable handling for travel or studio work.",
        "price": "12500.00",
        "rating": "3.50",
        "review_count": 10,
        "count_in_stock": 5,
        "image": "/assets/camera.svg",
    },
    {
        "name": "Sony WH-1000XM5 Headphones",
        "brand": "Sony",
        "category": "Audio",
        "description": "Noise-cancelling wireless headphones with soft ear cushions, long battery life, and rich sound for study, work, and travel.",
        "price": "29990.00",
        "rating": "4.80",
        "review_count": 248,
        "count_in_stock": 8,
        "image": "/assets/headphones.svg",
    },
    {
        "name": "Samsung Galaxy Watch 6",
        "brand": "Samsung",
        "category": "Wearables",
        "description": "A bright smartwatch with fitness tracking, sleep insights, notifications, and a clean circular design for everyday use.",
        "price": "18999.00",
        "rating": "4.20",
        "review_count": 89,
        "count_in_stock": 12,
        "image": "/assets/watch.svg",
    },
    {
        "name": "Dell XPS 13 Laptop",
        "brand": "Dell",
        "category": "Computers",
        "description": "Slim premium laptop with fast performance, edge-to-edge display, and lightweight build for productivity on the move.",
        "price": "84999.00",
        "rating": "4.60",
        "review_count": 64,
        "count_in_stock": 3,
        "image": "/assets/laptop.svg",
    },
]
